# Generated by Django 5.1.1 on 2024-12-01 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FishCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "鱼类分类",
                "verbose_name_plural": "鱼类分类",
            },
        ),
        migrations.CreateModel(
            name="WaterPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="水池名称")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置"
                    ),
                ),
                (
                    "size",
                    models.FloatField(blank=True, null=True, verbose_name="水池面积 (平方米)"),
                ),
                (
                    "depth",
                    models.FloatField(blank=True, null=True, verbose_name="水池深度 (米)"),
                ),
                (
                    "capacity",
                    models.FloatField(blank=True, null=True, verbose_name="水容量 (立方米)"),
                ),
                (
                    "water_temperature",
                    models.FloatField(blank=True, null=True, verbose_name="水温 (°C)"),
                ),
                (
                    "water_ph",
                    models.FloatField(blank=True, null=True, verbose_name="水的pH值"),
                ),
                (
                    "oxygen_level",
                    models.FloatField(
                        blank=True, null=True, verbose_name="溶解氧含量 (mg/L)"
                    ),
                ),
                (
                    "ammonia_level",
                    models.FloatField(
                        blank=True, null=True, verbose_name="氨氮浓度 (mg/L)"
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "水池信息",
                "verbose_name_plural": "水池信息",
            },
        ),
        migrations.CreateModel(
            name="FishGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="鱼类名称")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="养殖年龄"
                    ),
                ),
                (
                    "gender_ratio",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="雌雄比例"
                    ),
                ),
                (
                    "estimated_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="预估数量"),
                ),
                (
                    "avg_weight",
                    models.FloatField(blank=True, null=True, verbose_name="平均体重 (kg)"),
                ),
                (
                    "health_status",
                    models.CharField(default="健康", max_length=100, verbose_name="健康状态"),
                ),
                (
                    "health_alert",
                    models.TextField(blank=True, null=True, verbose_name="健康预警"),
                ),
                ("desc", models.TextField(blank=True, null=True, verbose_name="首页描述")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="fish/", verbose_name="鱼类图片"
                    ),
                ),
                ("content", models.TextField(help_text="富文本内容", verbose_name="富文本内容")),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fish_manage.fishcategory",
                        verbose_name="鱼类分类",
                    ),
                ),
                (
                    "water_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fish_manage.waterpool",
                        verbose_name="鱼类分布的水池",
                    ),
                ),
            ],
            options={
                "verbose_name": "鱼类信息",
                "verbose_name_plural": "鱼类信息",
            },
        ),
    ]
