# Generated by Django 5.1.1 on 2024-12-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish_manage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishgroup",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fish_category",
                to="fish_manage.fishcategory",
                verbose_name="鱼类分类",
            ),
        ),
    ]
