# Generated by Django 5.1.1 on 2024-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish_manage", "0002_alter_fishgroup_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishgroup",
            name="videos",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="视频"
            ),
        ),
    ]
