# Generated by Django 5.1.1 on 2024-12-07 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_listuserprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="listuserprofile",
            name="add_time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="添加时间"
            ),
        ),
    ]
